<!-- Davis Busteed -->

## Introduction

Linear regression is one of the most fundamental modeling techniques used in both descriptive and predictive statistics. When several *independent* variables are available to estimate a *dependent* variable, the Multiple Linear Regression (MLR) model is used.

Although it is possible to use MLR modeling without understanding the underlying mathematics, the following Notebook can give you a brief overview of how MLR really works.

## Getting Started

With a basic understanding of MLR, one should be aware that the MLR model is defined as

$$ {y_i} = {\beta_0} + {\beta_1}x_{i1} + {\beta_2}x_{i2} + \ldots + {\beta_k}x_{ik} + u_i $$

where $ y_i $ is the acutal value of the dependent variable for individual $ i $, $ \beta_0 $ is the intercept (or constant), $ \beta_1 \ldots \beta_k $ are the coefficients (or parameters) for their respective independent variables, and $ u_i $ is the error term that is unique to individual $ i $.

This model represents the entire *population* we are interested in. We won't be able to know the true values the $ \beta $ parameters, so the following *sample* model must be used to estimate the relationship between the independent variables and the dependent variable:

$$ \hat{y_i} = \hat{\beta_0} + \hat{\beta_1}x_{i1} + \hat{\beta_2}x_{i2} + \ldots + \hat{\beta_k}x_{ik} $$

Notice that $u_i$ isn't present in this model. During estimation, the true error term is unknonw to us. Instead, it will be calculated later, and refered to as the *residual*.

## Objective

Because the residuals are essentially a measure of how well the model describes the relationship in the data, **the objective of MLR is to find the parameters that will result in the smallest residuals**. In Ordinary Least-Squares Regression (OLS), this objective is formalized as finding the set of parameters that minimizes the sum of residuals squared. 

As mentioned above, we will never know the *true* values of the $\beta$ parameters; instead, we will derive a set of *estimators* that we can use to make inferences and predictions. 

## Transition to Matrix Notation

Before moving on, it is important to make sure that we can mathematically maniuplate our model in matrix notation. Since there is no limit to the number of independent variables that can be included in the model, matrix notation is the only realistic way to continue. 

As it is currently defined, the model inputs have the subscript $i$ to show that a different prediction will be made for each data point. We can visualize the data as every regression from $i$ to $n$.

$$ \hat{y_1} = \hat{\beta_0} + \hat{\beta_1}x_{11} + \hat{\beta_2}x_{12} + \ldots + \hat{\beta_k}x_{1k} $$

$$ \hat{y_2} = \hat{\beta_0} + \hat{\beta_1}x_{21} + \hat{\beta_2}x_{22} + \ldots + \hat{\beta_k}x_{2k} $$

$$ \vdots $$

$$ \hat{y_n} = \hat{\beta_0} + \hat{\beta_1}x_{n1} + \hat{\beta_2}x_{n2} + \ldots + \hat{\beta_k}x_{nk} $$

<br>
This series of different individual regressions can be grouped together into 3 matricies:

$$ \hat{Y} = 
\begin{bmatrix}
    y_1 \\
    y_2 \\
    \vdots \\
    y_n
\end{bmatrix}  
; \hat{\beta} = 
\begin{bmatrix}
    \beta_0 \\
    \beta_1 \\
    \vdots \\
    \beta_k
\end{bmatrix}
; X = 
\begin{bmatrix}
    1 & x_{11} & x_{12} & \dots & x_{1k} \\
    1 & x_{21} & x_{22} & \dots & x_{2k} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    1 & x_{n1} & x_{n2} & \dots & x_{nk} \\
\end{bmatrix}
$$

If you are familiar with matrix algebra, you will notice that $\hat{Y}$ is simply the dot product of $X$ and $\hat{\beta}$. Also notice that the $1$s in the first column of $X$. These are the values that will be mutiplied by the constant $\hat{\beta_0}$.



## Derive the estimator for $ \hat{\beta} $

With our matricies set up, we are now able to derive the estimator for $ \hat{\beta} $ in which the sum of square residuals will be minimized ( $ \min\sum{\hat{u_i^2} } $ ).

Before we start to minimize $ \sum{\hat{u_i^2}} $ with respect to $ \hat{\beta}, $ we can simplify $ \sum{\hat{u_i^2}} $ by separating $ {u_i}^2 $ into two matricies. By transposing one and bringing them back together, the sum of square residuals can be rewritten as $ \hat{U'}\hat{U} $, where $\hat{U}$ is a $(n x 1)$ matrix of residuals.

<br>
We can now derive the estimator that minimizes the sum of square residuals:

$$ \min{\hat{U'}\hat{U}} $$

<br>
From previous definitions we know that $\hat{U} = Y -\hat{Y}$ and $\hat{Y} = X\hat{\beta} $, therefore

$$ \min{ (Y -\hat{Y})'(Y -\hat{Y}) } $$

$$ \min{ (Y - X\hat{\beta})'(Y - X\hat{\beta}) } $$

$$ \min{ Y'Y - Y'X\hat{\beta} - (X\hat{\beta})'Y } + (X\hat{\beta})'X\hat{\beta}$$

$$ \min{ Y'Y - Y'X\hat{\beta} - \hat{\beta}'X'Y } + \hat{\beta}'X'X\hat{\beta}$$

$$ \min{ Y'Y - 2\hat{\beta}X'Y + \hat{\beta}'X'X\hat{\beta} }$$

<br>
To find the minimum of this expression in regards to $\hat{\beta}$, we will take the derivative, set it equal to zero, then solve for $\hat{\beta}$.

$$ \frac{\partial \hat{U'}\hat{U}}{\partial \hat{\beta}} = -2X'Y + 2X'X\hat{\beta} $$

$$ -2X'Y + 2X'X\hat{\beta} = 0 $$

$$ 2X'X\hat{\beta} = 2X'Y $$

$$ X'X\hat{\beta} = X'Y $$

$$ (X'X)^{-1}(X'X)\hat{\beta} = (X'X)^{-1}X'Y $$

$$ \hat{\beta} = (X'X)^{-1}X'Y $$

## Example With Data

Although there are numerous Python libraries that will do MLR for us, let's use the derivation of $\hat{\beta}$ to see how it works.

Let's load up a relatively small dataset. We will use tenure, IQ, and education level to wage.

In [52]:
# gotta have these!
import pandas as pd
import numpy as np

# load up the data
df = pd.read_csv('wage2.csv')

# look at a couple of records
df.head(5)

wage  tenure   IQ  educ
0   769       2   93    12
1   808      16  119    18
2   825       9  108    14
3   650       7   96    12
4   562       5   74    11

<br>
Next, we need to split the dataframe into two matricies, one for the dependent variable (Y), and the independent variables (X).

In [53]:
# Create a Numpy.matrix object so that we can use matrix operations

Y = np.matrix(df.wage).T
X = np.matrix([np.ones(len(df)), df.tenure, df.IQ, df.educ]).T

In [54]:
# Verify the Y matrix contains the first 5 values for wage

Y[:5]

matrix([[769],
        [808],
        [825],
        [650],
        [562]], dtype=int64)

In [57]:
# Verify the X matrix contains the X values for the first 5 individuals (as well as the column of ones)

X[:5]

matrix([[  1.,   2.,  93.,  12.],
        [  1.,  16., 119.,  18.],
        [  1.,   9., 108.,  14.],
        [  1.,   7.,  96.,  12.],
        [  1.,   5.,  74.,  11.]])

<br>
Now we can calculate the following $ \hat{\beta} = (X'X)^{-1}X'Y $

In [58]:
B = (X.T * X).I * X.T * Y

<br>
Let's look at the results. This matrix contains the parameters for our model.

In [59]:
B

matrix([[-199.55416715],
        [  10.3007383 ],
        [   4.85024855],
        [  43.93506431]])

<br>
Let's use the parameter values above to create a function for our sample model.

In [60]:
def predict_wage(t, iq, ed):
    
    # y = b0 + b1*tenure + b2*IQ + b3*educ
    
    return int(float(B[0]) + (float(B[1]) * t) + (float(B[2]) * iq) + (float(B[3]) * ed))

## Conclusion

Let's checkout a couple of the records and see how our sample regression model performed.

In [44]:
df.iloc[5:10]

wage  tenure   IQ  educ
5  1400       2  116    16
6   600       0   91    10
7  1081      14  114    18
8  1154       1  111    15
9  1000      16   95    12

In [47]:
for i in range(5,10):
    print(f"Actual: {df.iloc[i]['wage']} -- Predicted: {predict_wage(df.iloc[i]['tenure'], df.iloc[i]['IQ'], df.iloc[i]['educ'])}")

Actual: 1400 -- Predicted: 1086
Actual: 600 -- Predicted: 681
Actual: 1081 -- Predicted: 1288
Actual: 1154 -- Predicted: 1008
Actual: 1000 -- Predicted: 953


<br>
Our predictions weren't perfect, but this is the best the MLR could do.
<br><br>
Even though regression tools and libraries will take care of the matrix algebra for you, hopefully you found this example interesting.